# -*- coding: utf-8 -*-
"""RetainSpot_Churn_Model_Testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1icZpn_JwSZHQtE1DBemDVA5Hjw8NtSPk

# RetainSpot Customer Churn Prediction Models

## Imports
"""

# Utility
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import tqdm
import time
import joblib

# Models
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

# Training and Evaluation
from sklearn.model_selection import GridSearchCV, cross_val_score, StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix

"""## Data Loading"""

# Reading csv files into dataframes
X_train = pd.read_csv('/content/X_train.csv')
X_test = pd.read_csv('/content/X_test.csv')
y_train = pd.read_csv('/content/y_train.csv').values.ravel()
y_test = pd.read_csv('/content/y_test.csv').values.ravel()

X_train.head()

# Data has already been preprocessed, just need to scale few numerical columns
scaler = StandardScaler()
X_train[['tenure', 'MonthlyCharges', 'TotalCharges']] = scaler.fit_transform(X_train[['tenure', 'MonthlyCharges', 'TotalCharges']])
X_test[['tenure', 'MonthlyCharges', 'TotalCharges']] = scaler.transform(X_test[['tenure', 'MonthlyCharges', 'TotalCharges']])

# Show X_train after scaling:
X_train.head()

"""### Training Base Models"""

seed = 42

# BASE MODELS TO TRAIN
models = {
    'LogRegression': LogisticRegression(class_weight='balanced', random_state=seed),
    'LinearSVC': LinearSVC(class_weight='balanced', random_state=seed),
    'KNN': KNeighborsClassifier(),
    'DTree': DecisionTreeClassifier(class_weight='balanced', random_state=seed),
    'RandomForest': RandomForestClassifier(class_weight='balanced', random_state=seed),
    'XGB': XGBClassifier(random_state=seed),
}

param_grids = {
    'LogRegression': {
        'model__C': [0.01, 0.1, 1, 10, 100],
        'model__penalty': ['l2'],
        'model__solver': ['lbfgs', 'liblinear'],
        'model__class_weight': [None, 'balanced']
    },
    'LinearSVC': {
        'model__C': [0.01, 0.1, 1, 10],
        'model__class_weight': [None, 'balanced'],
        'model__loss': ['hinge', 'squared_hinge']
    },
    'KNN': {
        'model__n_neighbors': [3, 5, 7, 9, 11],
        'model__weights': ['uniform', 'distance'],
        'model__metric': ['euclidean', 'manhattan']
    },
    'DTree': {
        'model__max_depth': [3, 5, 7, 10, None],
        'model__min_samples_split': [2, 5, 10],
        'model__min_samples_leaf': [1, 2, 4],
        'model__class_weight': [None, 'balanced']
    },
    'RandomForest': {
        'model__n_estimators': [25, 50, 100, 200, 300],
        'model__max_depth': [5, 10, 15, None],
        'model__min_samples_split': [2, 5, 10],
        'model__class_weight': [None, 'balanced']
    },
    'XGB': {
        'model__n_estimators': [50, 100, 200, 300],
        'model__max_depth': [3, 5, 7],
        'model__learning_rate': [0.01, 0.1, 0.3],
        'model__scale_pos_weight': [1, 3, 5]
    }
}

# DEFINE PIPELINE
def create_pipeline(model):
  pipeline = Pipeline([
      ('scaler', StandardScaler()),
      ('model', model)
  ])
  return pipeline

# MODEL TRAINING METHOD
def train_model(model, X_train, y_train, X_test, y_test, model_name):
  # Train the model
  start_time = time.time()
  model.fit(X_train, y_train)
  train_time = time.time() - start_time

  # Get model predictions
  y_pred = model.predict(X_test)

  # Get Model Metrics
  metrics = {
      'Model': model_name,
      'Accuracy': accuracy_score(y_test, y_pred),
      'Precision': precision_score(y_test, y_pred),
      'Recall': recall_score(y_test, y_pred),
      'F1': f1_score(y_test, y_pred),
      'ROC_AUC': roc_auc_score(y_test, y_pred),
      'Training Time': train_time
  }

  return metrics, y_pred

# TRAIN BASE MODELS
def train_base_models(models):
  results = {}
  for model_name, model in models.items():
    print(f'TRAINING BASE MODEL {model_name}')
    metrics, y_pred = train_model(model, X_train, y_train, X_test, y_test, model_name)
    print(f'TRAINING COMPLETE.')
    print(f'METRICS:')
    print(f'ACCURACY: {metrics["Accuracy"]:.3f}')
    print(f'PRECISION: {metrics["Precision"]:.3f}')
    print(f'RECALL: {metrics["Recall"]:.3f}')
    print(f'F1: {metrics["F1"]:.3f}')
    print(f'ROC AUC: {metrics["ROC_AUC"]:.3f}')
    print(f'Training Time: {metrics["Training Time"]:.3f} sec\n')

train_base_models(models)

"""### Train Models with GridSearchCV"""

# TRAIN WITH GRID SEARCH
def train_with_gridsearch(models, X_train, y_train, X_test, y_test):

  results = []
  best_models = {}
  predictions = {}

  for model_name, model in models.items():

    # Create pipeline
    pipeline = create_pipeline(model)

    grid_search = GridSearchCV(
        pipeline,
        param_grids[model_name],
        cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=seed),
        scoring='f1',
        n_jobs=1,
        verbose=0
    )

    # Train using grid search
    print(f'TRAINING MODEL {model_name} WITH GRID SEARCH')
    start_time = time.time()
    grid_search.fit(X_train, y_train)
    train_time = time.time() - start_time
    print(f'TRAINING COMPLETE.')

    best_model = grid_search.best_estimator_
    best_params = grid_search.best_params_

    print(f'Best Parameters: {best_params}')
    print(f'Best CV Score: {grid_search.best_score_:.3f}')

    # Get predictions
    y_pred = best_model.predict(X_test)

    # Get Model Metrics
    metrics = {
      'Model': model_name,
      'Accuracy': accuracy_score(y_test, y_pred),
      'Precision': precision_score(y_test, y_pred),
      'Recall': recall_score(y_test, y_pred),
      'F1': f1_score(y_test, y_pred),
      'ROC_AUC': roc_auc_score(y_test, y_pred),
      'Training Time': train_time
    }

    print(f'METRICS:')
    print(f'ACCURACY: {metrics["Accuracy"]:.3f}')
    print(f'PRECISION: {metrics["Precision"]:.3f}')
    print(f'RECALL: {metrics["Recall"]:.3f}')
    print(f'F1: {metrics["F1"]:.3f}')
    print(f'ROC AUC: {metrics["ROC_AUC"]:.3f}')
    print(f'Training Time: {metrics["Training Time"]:.3f} sec\n')

    results.append(metrics)
    best_models[model_name] = best_model
    predictions[model_name] = y_pred

  return results, best_models, predictions


results = []
best_models = {}
predictions = {}

results, best_models, predictions = train_with_gridsearch(models, X_train, y_train, X_test, y_test)

"""#### Save the Random Forest Model"""

model = best_models["RandomForest"]
joblib.dump(model, "churn_model.pkl")

"""#### Adding Churn Scores (Model Probabilities) to Original Dataset"""

# Get original dataset and process
target = "Churn"
data = pd.read_csv('/content/telco_noisy_feedback_prep.csv')
data_clean = data.drop("Churn", axis=1)
data_clean = data_clean.drop(columns=[
    "CustomerFeedback",
    "sentiment",
    "feedback_length",
    "HasFeedback",
    "Unnamed: 0",
    "Unnamed: 0.1",
    "Churn",
    "customerID",
], errors="ignore")
data_clean.head()

print("Numeric columns:")
print(data_clean.select_dtypes(include=["int64", "float64"]).columns.tolist())

print("\nCategorical columns:")
print(data_clean.select_dtypes(include=["object"]).columns.tolist())

data_encoded = pd.get_dummies(data_clean, drop_first=True)
data_encoded = data_encoded.astype(int)
data_encoded.head()

bool_cols = data_encoded.select_dtypes(include="bool").columns
data_encoded[bool_cols] = data_encoded[bool_cols].astype(int)

data_encoded.head()

scaler = StandardScaler()
data_encoded[['tenure', 'MonthlyCharges', 'TotalCharges']] = scaler.fit_transform(data_encoded[['tenure', 'MonthlyCharges', 'TotalCharges']])
data_encoded.head()

"""##### Get Model Probabilities"""

y_proba = model.predict_proba(data_encoded)

# Append churn scores to dataset
data["Churn Score"] = y_proba[:, 1] * 100
data = data.drop("Churn", axis=1)
data.head()

data.to_csv("data_with_churn_score.csv", index=False)